config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post  = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Commenting on <%= @post.title %></h1>

<%= form_for [@post, @comment] do |f| %>
<%= f.label :comment %>
<%= f.text_area  :comment %>
<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPostsWorkshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing <%= @post.title %></h1>

<%= form_for @post do |f| %>
<p>
  <%= f.label :author, class: 'form-label' %>:
  <%= f.text_field :author %>
</p>
<p>
  <%= f.label :title, class: 'form-label' %>:
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body, class: 'form-label' %>
  <%= f.text_area :body %><br />
</p>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Viewing Posts</h1>

<%= link_to "New Post", new_post_path %>

<% @posts.each do |post| %>
<li>
  <%= link_to post.author, post_path(post) %>
</li>
<li>
  <%= post.title %>
</li>
<li>
  <%= post.body %>
</li>
<li>
  <% post.comments.each do |comment| %>
    <li><%= comment.comment %></li>
  <% end %>
</li>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
<p>
  <%= f.label :author, class: 'form-label' %>:
  <%= f.text_field :author %>
</p>
<p>
  <%= f.label :title, class: 'form-label' %>:
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body, class: 'form-label' %>
  <%= f.text_area :body %><br />
</p>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1>Showing <%= @post.title %></h1>
<li>
<%= @post.author %>
</li>
<li>
<%= @post.title %>
</li>
<li>
<%= @post.body %>
</li>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete %>
<%= link_to "Add Post", new_post_comment_path(@post) %>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>

<%= link_to "View Posts", posts_path  %>